 
language: java # Define the language
jdk: # Define the execution environments - openjdk11
- openjdk17
branches: # Execute job only on specific branch commits only:
  - development
before_script: - ls -la
script:
- mvn clean package
# Enter Maven root directory
# List all directory contents
# Build the project
after_success:
- echo “Process terminated successfully”
